/**
 * title: Catalog GUI
 * description: Responsible for generating and updating a GUI for the catalog client.
 * @author Dominic Evans
 * @date January 29, 2026
 * @version 1.0
 * @copyright 2026 Dominic Evans
 */

package catalog_application.client;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.file.Path;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import catalog_api.FileTracker;

public class CatalogGUI extends JFrame {

	private JTextArea consoleArea;
	private DefaultTableModel tableModel;
	private JTextField searchField;
	private JButton searchButton;
	private JButton downloadButton;
	private JTable fileTable;
	private FileTracker tracker;
	private String peerID;
	private Path downloadDir;

	/**
	 * The constructor of this class is responsible for defining and configuring the
	 * GUI interface for the Catalog Client. It additionally wires up all buttons
	 * with event handlers and redirects stdout and stderr to a built-in console for
	 * logging activities.
	 * 
	 * @param peerID identifying string generated by the IdentityManager.
	 */
	public CatalogGUI(String peerID, Path downloadDir) {
		/* Initialize Members */
		this.peerID = peerID;
		this.downloadDir = downloadDir;

		/* Set up the window */
		initGUI(this.peerID);

		/* Configure the action listeners */
		initActionListeners();

		/* Redirect stdout and stderr to the GUI console for logging */
		redirectSystemStreams();
	} // ctor

	/**
	 * Sets the FileTracker so that GUI elements can use it after it has been
	 * instantiated by CatalogClient during connection initialization.
	 * 
	 * @param tracker reference to a FileTracker for performing actions on the
	 *                remote server.
	 */
	public void setTracker(FileTracker tracker) {
		this.tracker = tracker;
		System.out.println("Tracker link established. Search enabled.");
		searchButton.setEnabled(true);
	} // setTracker

	/**
	 * This method is responsible for initializing the various GUI components with
	 * values. The GUI is composed of three sections: a title bar, a central file
	 * table, and a control/reporting panel at the bottom. The control elements
	 * include a search bar and button to execute searches as well as a download
	 * button that will download the file selected in the file table.
	 * 
	 * @param peerID the UUID that identifies the current client. This will be
	 *               displayed on top bar of the rendered window.
	 */
	private void initGUI(String peerID) {

		// Set up the window
		setTitle("P2P File Catalog - " + peerID);
		setSize(800, 600);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLayout(new BorderLayout(5, 5));

		// North: header with Peer ID
		JPanel northPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
		northPanel.add(new JLabel("Peer ID: " + peerID));
		add(northPanel, BorderLayout.NORTH);

		// Center: File Table
		String[] columnNames = { "File ID", "Filename" };
		this.tableModel = new DefaultTableModel(columnNames, 0);
		this.fileTable = new JTable(this.tableModel);
		add(new JScrollPane(this.fileTable), BorderLayout.CENTER);

		// South: Search Bar and Console
		JPanel southPanel = new JPanel(new BorderLayout());

		// Search sub-panel
		JPanel searchControls = new JPanel(new FlowLayout(FlowLayout.LEFT));
		this.searchField = new JTextField(30);
		this.searchButton = new JButton("Search Files");
		this.downloadButton = new JButton("Download");
		this.downloadButton.setEnabled(false);

		searchControls.add(new JLabel("Query:"));
		searchControls.add(this.searchField);
		searchControls.add(this.searchButton);
		searchControls.add(this.downloadButton);

		// Console sub-panel
		this.consoleArea = new JTextArea(10, 20);
		this.consoleArea.setEditable(false);
		this.consoleArea.setBackground(Color.BLACK);
		this.consoleArea.setForeground(Color.WHITE);
		this.consoleArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
		JScrollPane consoleScroll = new JScrollPane(consoleArea);

		southPanel.add(searchControls, BorderLayout.NORTH);
		southPanel.add(consoleScroll, BorderLayout.CENTER);
		add(southPanel, BorderLayout.SOUTH);
	} // initGUI

	private void initActionListeners() {
		// Cause a search to occur when return is entered in the search field or when
		// the search button is clicked
		this.searchButton.addActionListener(e -> handleSearch());
		this.searchField.addActionListener(e -> this.searchButton.doClick());
		this.downloadButton.addActionListener(e -> handleDownload());

		// Control the activation of the download button depending on whether or not a
		// file is selected in the UI
		fileTable.getSelectionModel().addListSelectionListener(e -> {
			if (!e.getValueIsAdjusting()) {
				int selectedRow = fileTable.getSelectedRow();
				// Activate the download button only if there is something selected
				// and that selection corresponds to a valid file
				String fileID = this.tableModel.getValueAt(selectedRow, 0).toString();
				downloadButton.setEnabled(selectedRow != -1 && !fileID.equals("N/A"));
			}
		});
	} // initActionListeners

	/**
	 * Creates a new anonymous OutputStream class for redirecting stdout and stderr
	 * to the GUI console rather than to the system console.
	 */
	private void redirectSystemStreams() {
		OutputStream out = new OutputStream() {
			@Override
			public void write(int b) {
				updateConsole(String.valueOf((char) b));
			}

			@Override
			public void write(byte[] b, int off, int len) {
				updateConsole(new String(b, off, len));
			}
		};
		System.setOut(new PrintStream(out, true));
		System.setErr(new PrintStream(out, true));
	} // redirectSystemStreams

	private void handleSearch() {
		String query = this.searchField.getText();
		// Be sure that the search actually has some text in it; if not, there's no
		// reason to continue
		if (query.trim().isEmpty()) {
			return;
		}

		// Disable the search button while a search thread is active to
		// limit thread generation
		this.searchButton.setEnabled(false);
		new Thread(() -> {
			try {
				System.out.println("[SYS] Querying server for: " + query);
				catalog_api.SearchResult[] results = this.tracker.searchFiles(query);

				// Update UI with results
				SwingUtilities.invokeLater(() -> {
					this.tableModel.setRowCount(0);
					// Check if any results were returned for a search; if not, display a message in
					// the results table
					if (results == null || results.length == 0) {
						this.tableModel.addRow(new Object[] { "N/A", "No files found for '" + query + "'", "N/A", 0 });
						System.out.println("[SYS] Search returned 0 results.");
					} else {
						for (catalog_api.SearchResult sr : results) {
							this.tableModel.addRow(new Object[] { sr.fileID, sr.fileName });
						}
					}
				});
			} catch (Exception ex) {
				System.err.println("[ERROR] Search failed: " + ex.getMessage());
			} finally {
				this.searchButton.setEnabled(true);
			}
		}).start();
	} // handleSearch

	private void handleDownload() {
		// Get the row number and return if no valid row is selected
		int row = this.fileTable.getSelectedRow();
		if (row == -1) {
			return;
		}

		// Check that the row is not being used for messaging the user, this
		// occurs when a search returns a "file not found" rather than a file name
		// to the file table
		String fileIDStr = this.tableModel.getValueAt(row, 0).toString();
		String fileNameStr = this.tableModel.getValueAt(row, 1).toString();
		if (fileIDStr.equals("N/A")) {
			return;
		}

		// Stop the user from creating a new thread before the download thread returns
		this.downloadButton.setEnabled(false);

		// Execute a new thread to download the file to keep the GUI responsive
		new Thread(() -> {
			try {
				// Parse the file ID from the table
				int fID = Integer.parseInt(fileIDStr);
				catalog_api.FileInfo finfo = tracker.getFileOwner(fID);

				// Download the file
				if (finfo != null) {
					System.out.println("Requesting: " + fileNameStr);
					FileRequester.downloadFile(finfo, downloadDir);
				} else {
					System.err.println(
							"[ERROR] Could not retrieve owner details for file '" + fileIDStr + "' from server.");
				}

			} catch (NumberFormatException nfe) {
				System.err.println("[ERROR] Download thread failed - Invalid File ID: " + nfe.getMessage());
			} catch (Exception e) {
				System.err.println("[ERROR] Download thread failed " + e.getMessage());
			} finally {
				this.downloadButton.setEnabled(true);
			}
		}).start();
	} // handleDownload

	/**
	 * Responsible for updating the JTextArea of the console with any outputs in a
	 * thread-safe manner.
	 * 
	 * @param text The output to be printed to the console
	 */
	private void updateConsole(String text) {
		SwingUtilities.invokeLater(() -> {
			this.consoleArea.append(text);
			this.consoleArea.setCaretPosition(consoleArea.getDocument().getLength());
		});
	} // updateConsole

}
