/**
 * title: Catalog GUI
 * description: Responsible for generating and updating a GUI for the catalog client.
 * @author Dominic Evans
 * @date January 29, 2026
 * @version 1.0
 * @copyright 2026 Dominic Evans
 */

package catalog_application.client;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.file.Path;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import catalog_api.FileTracker;

public class CatalogGUI extends JFrame {
	
	private JTextArea consoleArea;
	private DefaultTableModel tableModel;
	private JTextField searchField;
	private JButton searchButton;
	private JButton downloadButton;
	private FileTracker tracker;
	private Path downloadDir;
	
	/**
	 * The constructor of this class is responsible for defining and configuring the GUI interface
	 * for the Catalog Client. It additionally wires up all buttons with event handlers and redirects
	 * stdout and stderr to a built-in console for logging activities.
	 * 
	 * @param peerID identifying string generated by the IdentityManager.
	 */
	public CatalogGUI(String peerID, Path downloadDir) {
		this.downloadDir = downloadDir;
		
		// Set up the window
		setTitle("P2P File Catalog - " + peerID);
		setSize(800, 600);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLayout(new BorderLayout(5, 5));
		
		// North: header with Peer ID
		JPanel northPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
		northPanel.add(new JLabel("Peer ID: " + peerID));
		add(northPanel, BorderLayout.NORTH);
		
		// Center: File Table
		String[] columnNames = {"File ID", "Filename", "IP Address", "Port"};
		this.tableModel = new DefaultTableModel(columnNames, 0);
		JTable fileTable = new JTable(this.tableModel);
		add(new JScrollPane(fileTable), BorderLayout.CENTER);
		
		// South: Search Bar and Console
		JPanel southPanel = new JPanel(new BorderLayout());
		
		// Search sub-panel
		JPanel searchControls = new JPanel(new FlowLayout(FlowLayout.LEFT));
		this.searchField = new JTextField(30);
		this.searchButton = new JButton("Search Files");
		this.downloadButton = new JButton("Download");
		searchControls.add(new JLabel("Query:"));
		searchControls.add(this.searchField);
		searchControls.add(this.searchButton);
		searchControls.add(this.downloadButton);
		
		// Console sub-panel
		this.consoleArea = new JTextArea(10, 20);
		this.consoleArea.setEditable(false);
		this.consoleArea.setBackground(Color.BLACK);
		this.consoleArea.setForeground(Color.WHITE);
		this.consoleArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
		JScrollPane consoleScroll = new JScrollPane(consoleArea);
		
		southPanel.add(searchControls, BorderLayout.NORTH);
		southPanel.add(consoleScroll, BorderLayout.CENTER);
		add(southPanel, BorderLayout.SOUTH);

		// Redirect the system streams to the console for logging instead of the system console
		redirectSystemStreams();
		
		// Enable starting a search by pressing return
		this.searchField.addActionListener(e -> this.searchButton.doClick());
		
		/* SEARCH BUTTON */
		// Search button event handler
		this.searchButton.addActionListener(e -> {
			String query = this.searchField.getText();
			if (query.trim().isEmpty()) {
				return;
			}
			
			new Thread(() -> {
				try {
					System.out.println("[SYS] Querying server for: " + query);
					catalog_api.FileInfo[] results = this.tracker.searchFiles(query);
					
					// Update UI with results
					SwingUtilities.invokeLater(() -> {
						this.tableModel.setRowCount(0);
						// Check if any results were returned for a search; if not, display a message in the results table
						if (results == null || results.length == 0) {
							this.tableModel.addRow(new Object[] {
									"N/A", "No files found for '" + query + "'", "N/A", 0
							});
							System.out.println("[SYS] Search returned 0 results.");
						} else {
							for(catalog_api.FileInfo f : results) {
								this.tableModel.addRow(new Object[] {
										f.fileID, f.fileName, f.ownerIP, f.port
								});
							}
						}
					});
				} catch (Exception ex) {
					System.err.println("[ERROR] Search failed: " + ex.getMessage());
				}
			}).start();
		});
		
		/* DOWNLOAD BUTTON */
		// Download button is initially disabled until there is something selected to download
		this.downloadButton.setEnabled(false);

		// Control the activation of the download button depending on whether or not a file is selected in the UI
		fileTable.getSelectionModel().addListSelectionListener(e -> {
			if (!e.getValueIsAdjusting()) {
				int selectedRow = fileTable.getSelectedRow();
				// Activate the download button only if there is something selected and that selection 
				// corresponds to a valid file
				String fileID = this.tableModel.getValueAt(selectedRow, 0).toString();
				downloadButton.setEnabled(selectedRow != -1 && !fileID.equals("N/A"));
			}
		});

		// Download button event handler
		this.downloadButton.addActionListener(e -> {
			int row = fileTable.getSelectedRow();
			if (row == -1) {
				return;
			}
			
			String fileID = this.tableModel.getValueAt(row, 0).toString();
			if (fileID.equals("N/A")) {
				return;
			}
			
			// Pull the values of the selected FileInfo object from the selected table row
			String fileName = tableModel.getValueAt(row, 1).toString();
			String ownerIP = tableModel.getValueAt(row, 2).toString();
			int port = Integer.parseInt(tableModel.getValueAt(row, 3).toString());
			
			// Create a FileInfo object with the selected information
			catalog_api.FileInfo finfo = new catalog_api.FileInfo();
			try {
				finfo.fileID = Integer.parseInt(fileID);
				finfo.fileName = fileName;
				finfo.ownerIP = ownerIP;
				finfo.port = port;
			} catch (NumberFormatException nfe) {
				System.err.println("[ERROR] Corrupt file ID in table.");
			}
			
			// Execute a new thread to download the file to keep the GUI responsive
			new Thread(() -> {
				System.out.println("Requesting: " + fileName + " from " + ownerIP);
				FileRequester.downloadFile(finfo, downloadDir);
			}).start();
		});
	} //ctor

	/**
	 * Sets the FileTracker so that GUI elements can use it after it has been instantiated by
	 * CatalogClient during connection initialization.
	 * 
	 * @param tracker reference to a FileTracker for performing actions on the remote server.
	 */
	public void setTracker(FileTracker tracker) {
		this.tracker = tracker;
		System.out.println("Tracker link established. Search enabled.");
		searchButton.setEnabled(true);
	} // setTracker
	
	/**
	 * Creates a new anonymous OutputStream class for redirecting stdout and stderr to the GUI
	 * console rather than to the system console.
	 */
	private void redirectSystemStreams() {
		OutputStream out = new OutputStream () {
			@Override
			public void write(int b) {
				updateConsole(String.valueOf((char) b));
			}
			
			@Override
			public void write(byte[] b, int off, int len) {
				updateConsole(new String(b, off, len));
			}
		};
		System.setOut(new PrintStream(out, true));
		System.setErr(new PrintStream(out, true));
	} // redirectSystemStreams
	
	/**
	 * Responsible for updating the JTextArea of the console with any outputs in a thread-safe manner.
	 * 
	 * @param text The output to be printed to the console
	 */
	private void updateConsole(String text) {
		SwingUtilities.invokeLater(() -> {
			this.consoleArea.append(text);
			this.consoleArea.setCaretPosition(consoleArea.getDocument().getLength());
		});
	} // updateConsole

}












