package catalog_api;


/**
* catalog_api/_FileTrackerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

public class _FileTrackerStub extends org.omg.CORBA.portable.ObjectImpl implements catalog_api.FileTracker
{


  // Determines server configuration for maximum file lifetime without a heartbeat
  public int getTTL ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTTL", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTTL (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTTL


  // Allows a client to list file on the server for sharing
  public void listFile (String fileName, String ownerID, String ownerIP, int port)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listFile", true);
                $out.write_string (fileName);
                $out.write_string (ownerID);
                $out.write_string (ownerIP);
                $out.write_long (port);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                listFile (fileName, ownerID, ownerIP, port        );
            } finally {
                _releaseReply ($in);
            }
  } // listFile


  // Allow a client to delist a file on the server
  public void delistFile (String fileName, String ownerID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delistFile", true);
                $out.write_string (fileName);
                $out.write_string (ownerID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delistFile (fileName, ownerID        );
            } finally {
                _releaseReply ($in);
            }
  } // delistFile


  // Disconnect a client from the server and delist all of its shared files
  public void disconnect (String ownerID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("disconnect", true);
                $out.write_string (ownerID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                disconnect (ownerID        );
            } finally {
                _releaseReply ($in);
            }
  } // disconnect


  // Search for a file; does not reveal the owner of the file
  public catalog_api.SearchResult[] searchFiles (String query)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("searchFiles", true);
                $out.write_string (query);
                $in = _invoke ($out);
                catalog_api.SearchResult $result[] = catalog_api.searchResultsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return searchFiles (query        );
            } finally {
                _releaseReply ($in);
            }
  } // searchFiles


  // Get file information to enable initiating a file transfer
  public catalog_api.FileInfo getFileOwner (int fileID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFileOwner", true);
                $out.write_long (fileID);
                $in = _invoke ($out);
                catalog_api.FileInfo $result = catalog_api.FileInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getFileOwner (fileID        );
            } finally {
                _releaseReply ($in);
            }
  } // getFileOwner


  // Indicates to the server that the client is still present and sharing its directory
  public boolean keepAlive (String peerID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("keepAlive", true);
                $out.write_string (peerID);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return keepAlive (peerID        );
            } finally {
                _releaseReply ($in);
            }
  } // keepAlive

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:catalog_api/FileTracker:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "catalog_api._FileTrackerStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FileTrackerStub
