package catalog_api;


/**
* catalog_api/FileTrackerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Monday, January 26, 2026 2:32:55 AM MST
*/

public interface FileTrackerOperations 
{

  // Determines server configuration for maximum file lifetime without a heartbeat
  int getTTL ();

  // Allows a client to list file on the server for sharing
  void listFile (String fileName, String ownerID, String ownerIP, int port);

  // Allow a client to delist a file on the server
  void delistFile (String fileName, String ownerID);

  // Search for a file; does not reveal the owner of the file
  catalog_api.FileInfo[] searchFiles (String query);

  // Get file information to enable initiating a file transfer
  catalog_api.FileInfo getFileOwner (int fileID);

  // Indicates to the server that the client is still present and sharing its directory
  void keepAlive (String peerID);
} // interface FileTrackerOperations
