package catalog_api;


/**
* catalog_api/FileTracker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Thursday, January 22, 2026 9:23:15 PM MST
*/

public interface FileTracker extends FileTrackerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileTracker
