package catalog_api;


/**
* catalog_api/FileTrackerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Thursday, January 22, 2026 9:23:15 PM MST
*/

public abstract class FileTrackerPOA extends org.omg.PortableServer.Servant
 implements catalog_api.FileTrackerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("listFile", new java.lang.Integer (0));
    _methods.put ("delistFile", new java.lang.Integer (1));
    _methods.put ("searchFiles", new java.lang.Integer (2));
    _methods.put ("getFileOwner", new java.lang.Integer (3));
    _methods.put ("keepAlive", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Allows a client to list file on the server for sharing
       case 0:  // catalog_api/FileTracker/listFile
       {
         String fileName = in.read_string ();
         String ownerID = in.read_string ();
         String ownerIP = in.read_string ();
         int port = in.read_long ();
         this.listFile (fileName, ownerID, ownerIP, port);
         out = $rh.createReply();
         break;
       }


  // Allow a client to delist a file on the server
       case 1:  // catalog_api/FileTracker/delistFile
       {
         String fileName = in.read_string ();
         String ownerID = in.read_string ();
         this.delistFile (fileName, ownerID);
         out = $rh.createReply();
         break;
       }


  // Search for a file; does not reveal the owner of the file
       case 2:  // catalog_api/FileTracker/searchFiles
       {
         String query = in.read_string ();
         catalog_api.FileInfo $result[] = null;
         $result = this.searchFiles (query);
         out = $rh.createReply();
         catalog_api.fileListHelper.write (out, $result);
         break;
       }


  // Get file information to enable initiating a file transfer
       case 3:  // catalog_api/FileTracker/getFileOwner
       {
         String fileName = in.read_string ();
         catalog_api.FileInfo $result = null;
         $result = this.getFileOwner (fileName);
         out = $rh.createReply();
         catalog_api.FileInfoHelper.write (out, $result);
         break;
       }


  // Indicates to the server that the client is still present and sharing its directory
       case 4:  // catalog_api/FileTracker/keepAlive
       {
         String clientID = in.read_string ();
         int port = in.read_long ();
         this.keepAlive (clientID, port);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:catalog_api/FileTracker:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileTracker _this() 
  {
    return FileTrackerHelper.narrow(
    super._this_object());
  }

  public FileTracker _this(org.omg.CORBA.ORB orb) 
  {
    return FileTrackerHelper.narrow(
    super._this_object(orb));
  }


} // class FileTrackerPOA
