package catalog_api;


/**
* catalog_api/fileListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Monday, January 26, 2026 2:32:55 AM MST
*/

public final class fileListHolder implements org.omg.CORBA.portable.Streamable
{
  public catalog_api.FileInfo value[] = null;

  public fileListHolder ()
  {
  }

  public fileListHolder (catalog_api.FileInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = catalog_api.fileListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    catalog_api.fileListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return catalog_api.fileListHelper.type ();
  }

}
