package catalog_api;

/**
* catalog_api/FileTrackerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Tuesday, January 20, 2026 2:19:17 PM MST
*/

public final class FileTrackerHolder implements org.omg.CORBA.portable.Streamable
{
  public catalog_api.FileTracker value = null;

  public FileTrackerHolder ()
  {
  }

  public FileTrackerHolder (catalog_api.FileTracker initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = catalog_api.FileTrackerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    catalog_api.FileTrackerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return catalog_api.FileTrackerHelper.type ();
  }

}
