package catalog_api;


/**
* catalog_api/FileInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Thursday, January 22, 2026 9:23:15 PM MST
*/

public final class FileInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String fileName = null;
  public String ownerIP = null;
  public int port = (int)0;

  public FileInfo ()
  {
  } // ctor

  public FileInfo (String _fileName, String _ownerIP, int _port)
  {
    fileName = _fileName;
    ownerIP = _ownerIP;
    port = _port;
  } // ctor

} // class FileInfo
