package catalog_api;


/**
* catalog_api/FileTrackerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Thursday, January 22, 2026 9:23:15 PM MST
*/

abstract public class FileTrackerHelper
{
  private static String  _id = "IDL:catalog_api/FileTracker:1.0";

  public static void insert (org.omg.CORBA.Any a, catalog_api.FileTracker that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static catalog_api.FileTracker extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (catalog_api.FileTrackerHelper.id (), "FileTracker");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static catalog_api.FileTracker read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileTrackerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, catalog_api.FileTracker value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static catalog_api.FileTracker narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof catalog_api.FileTracker)
      return (catalog_api.FileTracker)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      catalog_api._FileTrackerStub stub = new catalog_api._FileTrackerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static catalog_api.FileTracker unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof catalog_api.FileTracker)
      return (catalog_api.FileTracker)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      catalog_api._FileTrackerStub stub = new catalog_api._FileTrackerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
