package catalog_api;


/**
* catalog_api/FileTracker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Tuesday, January 20, 2026 2:19:17 PM MST
*/

public interface FileTracker extends FileTrackerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileTracker
