package catalog_api;


/**
* catalog_api/FileTrackerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Thursday, January 22, 2026 9:23:15 PM MST
*/

public interface FileTrackerOperations 
{

  // Allows a client to list file on the server for sharing
  void listFile (String fileName, String ownerID, String ownerIP, int port);

  // Allow a client to delist a file on the server
  void delistFile (String fileName, String ownerID);

  // Search for a file; does not reveal the owner of the file
  catalog_api.FileInfo[] searchFiles (String query);

  // Get file information to enable initiating a file transfer
  catalog_api.FileInfo getFileOwner (String fileName);

  // Indicates to the server that the client is still present and sharing its directory
  void keepAlive (String clientID, int port);
} // interface FileTrackerOperations
