package catalog_api;


/**
* catalog_api/FileInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

public final class FileInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int fileID = (int)0;
  public String fileName = null;
  public String ownerIP = null;
  public int port = (int)0;

  public FileInfo ()
  {
  } // ctor

  public FileInfo (int _fileID, String _fileName, String _ownerIP, int _port)
  {
    fileID = _fileID;
    fileName = _fileName;
    ownerIP = _ownerIP;
    port = _port;
  } // ctor

} // class FileInfo
