package catalog_api;


/**
* catalog_api/nameListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Tuesday, January 20, 2026 2:19:17 PM MST
*/

public final class nameListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public nameListHolder ()
  {
  }

  public nameListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = catalog_api.nameListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    catalog_api.nameListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return catalog_api.nameListHelper.type ();
  }

}
