package catalog_api;


/**
* catalog_api/searchResultsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

abstract public class searchResultsHelper
{
  private static String  _id = "IDL:catalog_api/searchResults:1.0";

  public static void insert (org.omg.CORBA.Any a, catalog_api.SearchResult[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static catalog_api.SearchResult[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = catalog_api.SearchResultHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (catalog_api.searchResultsHelper.id (), "searchResults", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static catalog_api.SearchResult[] read (org.omg.CORBA.portable.InputStream istream)
  {
    catalog_api.SearchResult value[] = null;
    int _len0 = istream.read_long ();
    value = new catalog_api.SearchResult[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = catalog_api.SearchResultHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, catalog_api.SearchResult[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      catalog_api.SearchResultHelper.write (ostream, value[_i0]);
  }

}
