package catalog_api;


/**
* catalog_api/searchResultsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

public final class searchResultsHolder implements org.omg.CORBA.portable.Streamable
{
  public catalog_api.SearchResult value[] = null;

  public searchResultsHolder ()
  {
  }

  public searchResultsHolder (catalog_api.SearchResult[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = catalog_api.searchResultsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    catalog_api.searchResultsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return catalog_api.searchResultsHelper.type ();
  }

}
