package catalog_api;


/**
* catalog_api/SearchResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

public final class SearchResult implements org.omg.CORBA.portable.IDLEntity
{
  public int fileID = (int)0;
  public String fileName = null;

  public SearchResult ()
  {
  } // ctor

  public SearchResult (int _fileID, String _fileName)
  {
    fileID = _fileID;
    fileName = _fileName;
  } // ctor

} // class SearchResult
