package catalog_api;

/**
* catalog_api/SearchResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalog_api.idl
* Saturday, January 31, 2026 11:44:33 AM MST
*/

public final class SearchResultHolder implements org.omg.CORBA.portable.Streamable
{
  public catalog_api.SearchResult value = null;

  public SearchResultHolder ()
  {
  }

  public SearchResultHolder (catalog_api.SearchResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = catalog_api.SearchResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    catalog_api.SearchResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return catalog_api.SearchResultHelper.type ();
  }

}
